<div class="block account-nav">
    <div class="title">
        <strong><?= $block->escapeHtml(__('My Account')) ?></strong>
    </div>
    <div class="content">
        <nav class="account-nav">
            <ul class="nav items">
                <?= $block->getChildHtml() ?>
                <li class="nav item"><a href="http://magento.local/staff">Be a staff</a></li>
            </ul>
        </nav>
    </div>
</div>