<?php
/**
 * @var \Magenest\SagePay\Block\Adminhtml\System\Config\Fieldset\Version $block
 */
?>

<div>
    <h2 style="font-weight: bold;">
        <a target="_blank" href="https://store.magenest.com/">Magenest Affiliate</a>
    </h2>
    Version: <?= $block->getVersion() ?>
    <p>
<!--        Need support:-->
<!--        <a target="_blank" href="http://servicedesk.izysync.com/servicedesk/customer/portal/37">--><?//= __('Submit a ticket') ?><!--</a>-->
<!--        <br>-->
        Contact us:
        <a target="_blank" href="mailto:support@magenest.com"><?= __('support@magenest.com') ?></a>
    </p>
</div>