<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Your Personal Info')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Your Avatar')) ?></span>
            </strong>
            <div class="box-content">
                <img src="http://magento.local/admin/customer/index/viewfile/image/<?=base64_encode($block->getCustomValue());?>" alt="avatar"/>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Your Info')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?= $block->escapeHtml($block->getName()) ?><br>
                        <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                    </p>
                    <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>