<div class="table-wrapper">
    <table class="data table table-order-items history">
        <tbody>
            <tr>
                <th>Customer Email</th>
                <th>IP address</th>
                <th>Commission</th>
            </tr>
            <tr>
                <td>invited@gmail.com</td>
                <td>172.168.0.1</td>
                <td>$2.00</td>
            </tr>
            <tr>
                <td>invited@gmail.com</td>
                <td>172.168.0.2</td>
                <td>$2.00</td>
            </tr>
        </tbody>
    </table>
    <br/>
    <div>
        <strong>Total pay per lead: </strong> $4.00
    </div>
</div>