<div class="nav-sections sections">
    <div class="section-items nav-sections-items" style="padding: 10px">
        <Form>
            <label>From</label>
            <input type="date" name="from" id="from" value="5/11/19" autocomplete="on"/>
            <label>To</label>
            <input type="date" name="to" id="to" value="5/11/19" autocomplete="on"/>

            <button>Search</button>
        </Form>
    </div>
</div>

<div class="table-wrapper">
    <table class="data table table-order-items history">
        <tbody>
            <tr>
                <th>Clicks</th>
                <td>6</td>
                <th>Leads</th>
                <td>0</td>
            </tr>
            <tr>
                <th>Orders</th>
                <td>5</td>
                <th>Views</th>
                <td>5</td>
            </tr>
            <tr>
                <th>Total earned: </th><td> $58.00</td>
                <th> </th><td></td>
            </tr>
        </tbody>
    </table>
</div>