<div class="my-container">
    <div class="btn-group">
        <button class="btn-alert">Open Alert</button>
        <button class="btn">Open Model</button>
    </div>
    <div class="alert-content">
        <p>Hello World!!</p>
    </div>
    <div class="popup-content">
        <form id="popup-content-form">
            <b>First name: <font color="red">*</font></b>
            <input type="text" name="firstname"><br>
            <b>Last name: <font color="red">*</font></b>
            <input type="text" name="lastname">
        </form>
    </div>
</div>
<style>
    .popup-content, .alert-content{
        display:none;
    }
    #popup-content-form{
        width: 65%;
        background-color: #F0F0F0;
        padding: 40px;
        margin: auto;
    }
</style>