<?php

namespace Magenest\Movie\Block\Adminhtml\Model;
use Magento\Framework\App\Helper\AbstractHelper;
use Magento\Store\Model\ScopeInterface;
use Magenest\Movie\Helper\Data;
class CustomSelectList extends \Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray
{
    protected $helperData;
    public function __construct(
        \Magenest\Movie\Helper\Data $helperData
    )
    {
        $this->helperData = $helperData;

    }

    public function _prepareToRender()
    {
        $this->helperData->getConfigValue('salesforce/moviepage/select_field');
        parent::_prepareToRender(); // TODO: Change the autogenerated stub
    }

}
